"""Predefined comparison tables for parenting profiles.
Content designed to be non-diagnostic, empathetic, actionable — reviewed for clinical accuracy.
"""

COMPARISON_TABLES = [
    {
        "id": "adhd-baieti-vs-fete",
        "title": "ADHD la băieți vs ADHD la fete",
        "subtitle": "Cum arată ADHD-ul 'invizibil' la fete — adesea diagnosticat greșit ca anxietate/depresie",
        "left_label": "La băieți (tipar clasic)",
        "right_label": "La fete (tipar invizibil)",
        "icon": "female",
        "color": "#B56B6B",
        "rows": [
            {"label": "Manifestare motorie", "left": "Aleargă, se cațără, 'motor pornit continuu'", "right": "Se foiește discret — joacă cu părul, unghii, își schimbă poziția des"},
            {"label": "Atenție", "left": "Distras rapid de stimuli exteriori (sunete, mișcare)", "right": "Visează cu ochii deschiși, 'plutește' în propriile gânduri"},
            {"label": "Emoții", "left": "Explozii vizibile, furie deschisă, agresivitate", "right": "Autocritică severă, plâns în singurătate, 'nu sunt destul de bună'"},
            {"label": "Școală", "left": "Deranjează colegii, este mustrat, ia note mici", "right": "'Copil bun/cuminte', ia note bune cu efort uriaș, uită temele acasă"},
            {"label": "Socializare", "left": "Impulsiv, întrerupe, poate fi respins de colegi", "right": "Hipersensibilă social, evită conflicte, se retrage, mimică perfectă"},
            {"label": "Diagnostic frecvent", "left": "ADHD hiperactiv-impulsiv (detectat corect)", "right": "❌ Anxietate / Depresie (greșit — nu se caută ADHD)"},
            {"label": "Vârstă la diagnostic", "left": "5–8 ani", "right": "15–30 ani (adesea în facultate, când presiunea o rupe)"},
            {"label": "Ce vede părintele", "left": "'Nu stă locului o clipă'", "right": "'E o fetiță visătoare, dar epuizată. Nu înțeleg de ce.'"},
        ],
        "insight": "Cheia: dacă fata ta pare 'liniștită dar epuizată', este perfecționistă până la anxietate, sau se autocritică des — cereți o evaluare pentru ADHD inatentiv la un psiholog clinician pediatric care lucrează cu profile atipice.",
    },
    {
        "id": "ticuri-vs-hiperkinezie",
        "title": "Tulburare de ticuri vs Hiperkinezie (agitație motorie)",
        "subtitle": "Ambele înseamnă 'multă mișcare', dar sunt esențial diferite ca origine",
        "left_label": "Ticuri",
        "right_label": "Hiperkinezie",
        "icon": "hand-right",
        "color": "#DE8F6E",
        "rows": [
            {"label": "Tipul de mișcare", "left": "Gest PRECIS, repetitiv, mereu la fel (clipire, ridicare umeri, dres de voce)", "right": "Mișcare GENERALĂ a corpului — se foiește, aleargă, sare, schimbă poziția"},
            {"label": "Origine", "left": "Un impuls interior ('senzație de tensiune') pe care copilul îl 'descarcă'", "right": "Prea multă energie fără loc unde să meargă — 'motor pornit continuu'"},
            {"label": "Poate opri voluntar?", "left": "Da, câteva secunde — dar tensiunea crește și 'explodează'", "right": "Nu prea — e o stare constantă, nu un act singular"},
            {"label": "Se agravează cu", "left": "Stres, oboseală, atenție concentrată", "right": "Restricție (când trebuie să stea nemișcat), plictis"},
            {"label": "Dispare?", "left": "În somn, uneori spontan la vârsta 12–15 ani", "right": "Persistă zilnic, dar se atenuează cu structură și mișcare"},
            {"label": "Reacția părintelui recomandată", "left": "❌ NU cereți copilului să 'se oprească' — crește tensiunea", "right": "✅ Oferiți pauze de mișcare, mediu cu structură clară"},
            {"label": "Specialistul potrivit", "left": "Neurolog pediatru, psiholog clinician", "right": "Psiholog clinician, uneori psihiatru pediatru"},
        ],
        "insight": "Un părinte poate diferenția singur: filmați copilul 2 minute cu telefonul. Dacă e aceeași mișcare precisă (ex: clipire) → probabil tic. Dacă e agitație variată → probabil hiperkinezie. Duceți filmulețul la specialist.",
    },
    {
        "id": "adhd-vs-anxietate",
        "title": "ADHD vs Anxietate la copil",
        "subtitle": "Foarte des confundate — mai ales la fete și adolescenți",
        "left_label": "ADHD",
        "right_label": "Anxietate",
        "icon": "pulse",
        "color": "#7A9E9F",
        "rows": [
            {"label": "Sursa neatenției", "left": "Mintea 'sare' între idei — 10 ferestre deschise", "right": "Mintea e blocată pe grijă/scenariu de rău"},
            {"label": "Somn", "left": "Adoarme greu (nu se 'oprește'), somn agitat", "right": "Adoarme cu frică, coșmaruri, se trezește neliniștit"},
            {"label": "Reacție la sarcină nouă", "left": "Începe rapid, dar nu termină", "right": "Amână, se blochează, se teme de greșeli"},
            {"label": "Emoții tipice", "left": "Frustrare, plictis, impulsivitate", "right": "Frică, îngrijorare, hipervigilență"},
            {"label": "Ce spune copilul", "left": "'M-am plictisit', 'e boring'", "right": "'Dacă se întâmplă ceva rău?', 'Dacă greșesc?'"},
            {"label": "Corpul", "left": "Nu stă locului, se foiește", "right": "Dureri de burtă, cap, palpitații, tremurături"},
            {"label": "Ambele pot coexista?", "left": "Da — 60% din copiii cu ADHD au și anxietate", "right": "Da — anxietatea poate masca ADHD-ul (mai ales la fete)"},
        ],
        "insight": "Dacă anxietatea copilului tău a apărut brusc la vârsta 10-15 ani și e însoțită de oboseală mentală cronică, cereți o evaluare completă — nu doar pentru anxietate, ci și pentru ADHD inatentiv nediagnosticat în copilărie.",
    },
    {
        "id": "obraznic-vs-adhd",
        "title": "Copil 'obraznic' vs Copil cu ADHD",
        "subtitle": "Când comportamentul dificil are o cauză neurologică, nu una educațională",
        "left_label": "Copil 'obraznic' (educațional)",
        "right_label": "Copil cu ADHD (neurologic)",
        "icon": "warning",
        "color": "#E8C37C",
        "rows": [
            {"label": "Auzi regula, dar nu o respecți?", "left": "Alege să nu o respecte — testează limitele", "right": "Uită regula după 5 minute — nu e alegere"},
            {"label": "Se calmează după 'gata!'", "left": "Da, cu efort, se controlează", "right": "Nu — vrea, dar nu poate. Se frustrează și mai tare"},
            {"label": "Când e obosit", "left": "Devine mai ascultător (are nevoie de somn)", "right": "Devine mai agitat, paradoxal"},
            {"label": "Consistență în comportament", "left": "Consistent — testează limitele mereu", "right": "Foarte inconsistent — 'azi e alt copil'"},
            {"label": "Răspunde la pedepse?", "left": "Da — învață din consecințe", "right": "Nu prea — pedeapsa creează rușine, nu învățare"},
            {"label": "Ce funcționează", "left": "Reguli clare, consecvență, autoritate blândă", "right": "Structură previzibilă, celebrare a micilor progrese, terapie ocupațională"},
            {"label": "Sentimentul părintelui", "left": "'Trebuie să fiu mai ferm'", "right": "'Ceva nu e ok, mă simt neputincios'"},
        ],
        "insight": "Un indiciu major: dacă disciplina normală (care funcționează cu alți copii sau chiar cu frații lui) nu funcționează după 6 luni de consecvență, e semn că nu e o problemă de educație. Consultați un psiholog clinician pediatric.",
    },
    {
        "id": "adhd-hiperactiv-vs-inatentiv",
        "title": "ADHD hiperactiv-impulsiv vs ADHD inatentiv",
        "subtitle": "Aceeași tulburare, două fețe complet diferite",
        "left_label": "Hiperactiv-impulsiv",
        "right_label": "Inatentiv (adesea 'ADD')",
        "icon": "flash",
        "color": "#9B8CC4",
        "rows": [
            {"label": "Mișcare", "left": "Foarte multă — aleargă, se cațără, vorbește neîntrebat", "right": "Puțină vizibilă — pare 'cu capul în nori'"},
            {"label": "Atenție", "left": "Se distrage la ORICE stimul exterior", "right": "Se pierde în GÂNDURILE proprii — visare"},
            {"label": "Când se vede clar", "left": "În public, la școală, în orice mediu", "right": "Doar când e o sarcină obositoare — pare normal altfel"},
            {"label": "Cine e mai afectat", "left": "Mai frecvent la băieți (dar nu exclusiv)", "right": "Mai frecvent la fete, dar și băieți liniștiți"},
            {"label": "Impact școlar", "left": "Note mici + probleme comportamentale", "right": "Note bune cu efort uriaș, dar 'nu-și dă silința suficient'"},
            {"label": "Diagnostic", "left": "Detectat devreme (5-8 ani)", "right": "Detectat târziu (11-25 ani), sau niciodată"},
            {"label": "Sentimentul copilului", "left": "'Sunt rău, deranjez, nimeni nu mă place'", "right": "'Sunt proastă, sunt lentă, nu sunt destul de bună'"},
        ],
        "insight": "Poți avea și ambele forme combinate (numit 'ADHD combinat'). Ce contează e ca specialistul să evalueze COMPLET, nu doar simptomele evidente motorii.",
    },
    {
        "id": "supradotare-vs-2e",
        "title": "Copil supradotat vs Copil dublu-excepțional (2e)",
        "subtitle": "Supradotare + ADHD/dislexie/anxietate — profile care se maschează reciproc",
        "left_label": "Supradotat 'clasic'",
        "right_label": "Dublu excepțional (2e)",
        "icon": "sparkles",
        "color": "#5E8B7E",
        "rows": [
            {"label": "Performanță școlară", "left": "Excelentă, constantă, aparent fără efort", "right": "Foarte inconsistentă — geniu la ce iubește, blocat la ce urăște"},
            {"label": "Cum e văzut", "left": "'Copil minune', 'perfect'", "right": "'Poate mai mult, dar e leneș', 'nu-și dă silința'"},
            {"label": "Testul de IQ", "left": "Scor uniform înalt", "right": "Scor foarte înalt la unele probe, foarte scăzut la altele"},
            {"label": "Emoții", "left": "Sensibilitate moderată, se adaptează", "right": "Intense — perfecționism paralizant, frustrare extremă"},
            {"label": "Interese", "left": "Curiozitate largă, învață rapid", "right": "Obsesiv pe 1-2 pasiuni, ignoră restul"},
            {"label": "Ce ratează școala", "left": "Se plictisește, dar rezolvă", "right": "Nu-și termină sarcinile, pare 'delăsat', primește note mai mici decât capacitatea reală"},
            {"label": "Risc major", "left": "Presiune, epuizare la adolescență", "right": "Ignorat, catalogat ca 'leneș', pierde încrederea în sine"},
        ],
        "insight": "Un copil 2e are nevoie de o evaluare psihologică specializată — nu doar test de IQ, ci și evaluare pentru ADHD/dislexie/anxietate. Multe centre nu detectează 2e pentru că 'compensează prea bine'.",
    },
    {
        "id": "sensibilitate-vs-depresie",
        "title": "Copil sensibil emoțional vs Copil cu depresie",
        "subtitle": "Când sensibilitatea firească se transformă în semnal de alarmă",
        "left_label": "Sensibilitate emoțională (temperament)",
        "right_label": "Depresie clinică",
        "icon": "heart",
        "color": "#B56B6B",
        "rows": [
            {"label": "Cât durează starea", "left": "Ore, maxim 1-2 zile", "right": "Peste 2 săptămâni fără pauze"},
            {"label": "Ce declanșează", "left": "Un eveniment identificabil (ceartă, mustrare)", "right": "Nimic clar — 'așa mă simt'"},
            {"label": "Bucurie", "left": "Se bucură intens și des", "right": "Nu se mai bucură de nimic — anhedonia"},
            {"label": "Somn", "left": "Normal, uneori mai lung după emoții intense", "right": "Insomnie sau hipersomnie persistentă"},
            {"label": "Apetit", "left": "Normal", "right": "Refuză mâncarea SAU mănâncă compulsiv"},
            {"label": "Autopercepție", "left": "'Sunt trist acum, dar sunt bine'", "right": "'Sunt inutil', 'nimeni nu m-ar duce lipsă', 'sunt povară'"},
            {"label": "Când să consultați", "left": "Dacă vă preocupă intensitatea", "right": "URGENT dacă vedeți semnele de mai sus persistând peste 2 săptămâni"},
        ],
        "insight": "Semnale RED FLAG care cer consult psihiatric pediatric urgent: menționează moartea, spune 'aș vrea să dispar', se izolează total, refuză școala săptămâni. Nu ezitați — cereți ajutor imediat.",
    },
    {
        "id": "asd-vs-adhd",
        "title": "Autism (ASD) vs ADHD",
        "subtitle": "Ambele afectează atenția și socializarea, dar mecanismul e diferit",
        "left_label": "Autism (ASD)",
        "right_label": "ADHD",
        "icon": "puzzle",
        "color": "#6E8FD8",
        "rows": [
            {"label": "Contactul vizual", "left": "Redus sau evitat consecvent", "right": "Prezent, dar 'sare' la altceva rapid"},
            {"label": "Interacțiune socială", "left": "Nu înțelege semnalele sociale — 'literal'", "right": "Le înțelege, dar nu le respectă (întrerupe, își impune)"},
            {"label": "Rutinele", "left": "Extrem de importante — schimbarea provoacă criză", "right": "Detestă rutinele, caută variație"},
            {"label": "Interese", "left": "Obsesive, foarte restrânse, mult detaliu", "right": "Multiple, superficiale, se schimbă rapid"},
            {"label": "Sensibilități senzoriale", "left": "Frecvente și intense (zgomote, texturi, gust)", "right": "Uneori (mai ales pe zgomot)"},
            {"label": "Vorbire", "left": "Poate avea întârziere, ton monoton, vocabular avansat", "right": "Normală, dar vorbește excesiv/impulsiv"},
            {"label": "Poți avea ambele?", "left": "Da — 50-70% dintre cei cu ASD au și ADHD", "right": "Da — se combină frecvent"},
        ],
        "insight": "Un logoped sau psiholog cu specializare în tulburări de neurodezvoltare poate diferenția corect. Diagnostic diferențial se face cu ADI-R, ADOS-2 pentru ASD și teste standardizate pentru ADHD.",
    },
    {
        "id": "timid-vs-anxietate-sociala",
        "title": "Copil 'timid' vs Anxietate socială",
        "subtitle": "Când timiditatea normală devine o barieră",
        "left_label": "Timiditate (temperament)",
        "right_label": "Anxietate socială",
        "icon": "eye-off",
        "color": "#E8C37C",
        "rows": [
            {"label": "Cu cine e închis", "left": "Doar cu străinii", "right": "Cu toată lumea în afara familiei — inclusiv colegii cunoscuți"},
            {"label": "După ce se 'sparge gheața'", "left": "Interacționează normal", "right": "Rămâne blocat, transpira, îi tremură vocea"},
            {"label": "Corp", "left": "Roșeață trecătoare", "right": "Tremurături, tahicardie, greață înainte de eveniment social"},
            {"label": "Anticipare", "left": "Poate fi anxios înainte, dar merge", "right": "Refuză categoric — 'nu mă duc', 'mă doare burta'"},
            {"label": "Prieteni", "left": "Are 1-2 prieteni apropiați", "right": "Nu are prieteni sau are doar unul virtual"},
            {"label": "Impact școlar", "left": "Ia note bune, nu ridică mâna", "right": "Absentează, refuză prezentări orale, scade la note"},
            {"label": "Ce ajută", "left": "Timp, expunere blândă", "right": "Terapie cognitiv-comportamentală (CBT) cu psiholog"},
        ],
        "insight": "Dacă copilul refuză școala mai mult de 3 zile pe lună din cauze sociale, sau spune că 'nu poate respira' înainte de evenimente, e semn că trebuie consult specialist. Anxietatea socială netratată devine cronică.",
    },
    {
        "id": "ticuri-motorii-vs-vocale",
        "title": "Ticuri motorii vs ticuri vocale",
        "subtitle": "Cum le recunoști și când e nevoie de consult",
        "left_label": "Ticuri motorii",
        "right_label": "Ticuri vocale",
        "icon": "hand-left",
        "color": "#DE8F6E",
        "rows": [
            {"label": "Exemple", "left": "Clipire, ridicare umeri, strâmbături, atingere obiecte", "right": "Dres de voce, tuse, țipăt scurt, cuvinte repetate, 'hm-hm'"},
            {"label": "Cine le observă primul", "left": "Părintele — vizuale", "right": "Profesorul / colegii — auditive"},
            {"label": "Ruşine socială", "left": "Moderată — pot fi ascunse", "right": "Mai mare — copilul evită să vorbească"},
            {"label": "Sindromul Tourette", "left": "Necesar prezent (peste 1 an)", "right": "Necesar prezent (peste 1 an) — DOAR ambele TIPURI + peste 12 luni"},
            {"label": "Cauze frecvente", "left": "Stres, oboseală, anxietate", "right": "Stres, oboseală, anxietate — la fel"},
            {"label": "Ce agravează", "left": "Comentariile părintelui ('nu mai face!')", "right": "Silința să 'vorbească normal' în public"},
            {"label": "Ce specialist", "left": "Neurolog pediatric + psiholog", "right": "Neurolog pediatric + psiholog + eventual logoped"},
        ],
        "insight": "Cheia de aur: NU corectați copilul când face ticul. Ticul e o descărcare — cu cât îl reprimă, cu atât tensiunea crește și ticul revine mai puternic. Structura calmă, somnul bun și diminuarea stresului sunt primele intervenții.",
    },
]


COMPARISON_MAP = {c["id"]: c for c in COMPARISON_TABLES}
